site:
  name: Percetakan Makassar
  site: 'https://percetakanmakassar.web.id' # Ganti dengan URL Cloudflare Pages kamu jika sudah ada
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null # Biarkan null dulu sampai kamu punya kode dari Google Search Console

# Pengaturan SEO Bawaan
metadata:
  title:
    default: Percetakan Makassar - Jasa Cetak Kilat & Murah
    template: '%s — Percetakan Makassar'
  description: 'Butuh Percetakan Kilat di Makassar ? Cuma di Sini Tempatnya! Kualitas Warna Tajam, Harga Teman se-Makassar. Cek Promo Hari Ini Sebelum Antrian Penuh!'
  robots:
    index: false
    follow: false
  openGraph:
    siteName: Percetakan Makassar
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: null
    site: null
    cardType: summary_large_image

# Pengaturan Bahasa (Sinkronisasi Indonesia)
i18n:
  language: id
  textDirection: ltr

# Pengaturan Fitur Blog
apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/blog/%slug%' # Mencegah konflik dengan halaman statis
      robots:
        index: false

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: true
      pathname: 'kategori' # Diubah ke bahasa Indonesia
      robots:
        index: false

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false # Tetap false untuk menghindari isu konten ganda (Duplicate Content) di SEO

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Isi jika kamu sudah punya ID Google Analytics

ui:
  theme: 'system' # Mengikuti pengaturan mode gelap/terang di HP/Laptop pengunjung
